version: '3.2'

#services:
#  web:
#    build: .
#    command: sh -c "uvicorn app:app --reload --port=8080 --host=0.0.0.0"
#    ports:
#      - 8080:8080
#

services:
  restapi:
    image: localhost:5000/restapi
    entrypoint: "uvicorn app:app --reload --port=8080 --host=0.0.0.0"
    ports:
      - "8080:8080"
#    environment:
    volumes:
      - ./:/app/
      - ./debug.log:/app/debug.log:rw
    user: lacinaslair
    restart: on-failure
#    depends_on:
#      - flowroutedb
#      - localstack
#      - smtpd.internal
#