call python main.py load -f ".\datafiles\2023\Capital One.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\CareCredit.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\Chase.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\HomeDepot.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\Sound Checking Christa.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\Sound Savings.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\Sound Visa.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\Wells Fargo Checking.csv" -o 8 -n "Full Test"
call python main.py load -f ".\datafiles\2023\Wells Fargo Visa.csv" -o 8 -n "Full Test"
