
export const templates = [
    {
        "id": 20,
        "credit": false,
        "hint": "Loan Payment",
        "notes": "",
        "category": {
            "id": 14,
            "value": "Loan"
        },
        "institution": {
            "id": 1,
            "key": "WLS_CHK",
            "name": "Wellsfargo Checking"
        },
        "tags": [
            {
                "id": 4,
                "value": "Recurring"
            },
            {
                "id": 7,
                "value": "Loan"
            }
        ],
        "qualifiers": [
            {
                "id": 83,
                "value": "ONLINE TRANSFER REF ",
                "institution_id": 1
            },
            {
                "id": 84,
                "value": " TO INSTALLMENT LOANS XXXXXX49130001",
                "institution_id": 1
            }
        ]
    }
];

export const transactions = [
  {
    "id": 1,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-04-13",
    "transaction_data": [
      "2023-04-13",
      "2023-04-13",
      "7776",
      "CAPITAL ONE ONLINE PYMT",
      "Payment/Credit",
      "",
      "100.00"
    ],
    "tags": null,
    "description": "CAPITAL ONE ONLINE PYMT",
    "amount": 100
  },
  {
    "id": 2,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-04-03",
    "transaction_data": [
      "2023-04-03",
      "2023-04-03",
      "7776",
      "INTEREST CHARGE:PURCHASES",
      "Fee/Interest Charge",
      "11.29",
      ""
    ],
    "tags": null,
    "description": "INTEREST CHARGE:PURCHASES",
    "amount": -11.29
  },
  {
    "id": 3,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-04-02",
    "transaction_data": [
      "2023-04-02",
      "2023-04-03",
      "7776",
      "Amazon web services",
      "Other Services",
      "1.76",
      ""
    ],
    "tags": null,
    "description": "Amazon web services",
    "amount": -1.76
  },
  {
    "id": 4,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-03-14",
    "transaction_data": [
      "2023-03-14",
      "2023-03-14",
      "7776",
      "CAPITAL ONE ONLINE PYMT",
      "Payment/Credit",
      "",
      "50.00"
    ],
    "tags": null,
    "description": "CAPITAL ONE ONLINE PYMT",
    "amount": 50
  },
  {
    "id": 5,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-03-03",
    "transaction_data": [
      "2023-03-03",
      "2023-03-03",
      "7776",
      "INTEREST CHARGE:PURCHASES",
      "Fee/Interest Charge",
      "1.41",
      ""
    ],
    "tags": null,
    "description": "INTEREST CHARGE:PURCHASES",
    "amount": -1.41
  },
  {
    "id": 6,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-03-02",
    "transaction_data": [
      "2023-03-02",
      "2023-03-03",
      "7776",
      "Amazon web services",
      "Other Services",
      "1.76",
      ""
    ],
    "tags": null,
    "description": "Amazon web services",
    "amount": -1.76
  },
  {
    "id": 7,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-02-23",
    "transaction_data": [
      "2023-02-23",
      "2023-02-24",
      "7776",
      "TM *PNK TRUSTFALL TOUR",
      "Entertainment",
      "381.82",
      ""
    ],
    "tags": null,
    "description": "TM *PNK TRUSTFALL TOUR",
    "amount": -381.82
  },
  {
    "id": 8,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-02-18",
    "transaction_data": [
      "2023-02-18",
      "2023-02-23",
      "7776",
      "U-HAUL-CTR-12TH-L #70221",
      "Car Rental",
      "99.10",
      ""
    ],
    "tags": null,
    "description": "U-HAUL-CTR-12TH-L #70221",
    "amount": -99.1
  },
  {
    "id": 9,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-02-15",
    "transaction_data": [
      "2023-02-15",
      "2023-02-15",
      "7776",
      "CAPITAL ONE ONLINE PYMT",
      "Payment/Credit",
      "",
      "152.84"
    ],
    "tags": null,
    "description": "CAPITAL ONE ONLINE PYMT",
    "amount": 152.84
  },
  {
    "id": 10,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-02-03",
    "transaction_data": [
      "2023-02-03",
      "2023-02-03",
      "7776",
      "INTEREST CHARGE:PURCHASES",
      "Fee/Interest Charge",
      "3.77",
      ""
    ],
    "tags": null,
    "description": "INTEREST CHARGE:PURCHASES",
    "amount": -3.77
  },
  {
    "id": 11,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-02-02",
    "transaction_data": [
      "2023-02-02",
      "2023-02-03",
      "7776",
      "Amazon web services",
      "Other Services",
      "1.76",
      ""
    ],
    "tags": null,
    "description": "Amazon web services",
    "amount": -1.76
  },
  {
    "id": 12,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-01-12",
    "transaction_data": [
      "2023-01-12",
      "2023-01-12",
      "7776",
      "CAPITAL ONE ONLINE PYMT",
      "Payment/Credit",
      "",
      "200.00"
    ],
    "tags": null,
    "description": "CAPITAL ONE ONLINE PYMT",
    "amount": 200
  },
  {
    "id": 13,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-01-03",
    "transaction_data": [
      "2023-01-03",
      "2023-01-05",
      "7776",
      "ROUND TABLE PIZZA 821",
      "Dining",
      "32.75",
      ""
    ],
    "tags": null,
    "description": "ROUND TABLE PIZZA 821",
    "amount": -32.75
  },
  {
    "id": 14,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-01-02",
    "transaction_data": [
      "2023-01-02",
      "2023-01-03",
      "7776",
      "Amazon web services",
      "Other Services",
      "1.76",
      ""
    ],
    "tags": null,
    "description": "Amazon web services",
    "amount": -1.76
  },
  {
    "id": 15,
    "batch_id": 1,
    "institution_id": 3,
    "transaction_date": "2023-01-02",
    "transaction_data": [
      "2023-01-02",
      "2023-01-03",
      "7776",
      "CT LOCKSMITH",
      "Professional Services",
      "312.80",
      ""
    ],
    "tags": null,
    "description": "CT LOCKSMITH",
    "amount": -312.8
  },
  {
    "id": 16,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-05-02",
    "transaction_data": [
      "05/02/2023",
      "05/03/2023",
      "Kindle Unltd*EL3SL17V3",
      "Shopping",
      "Sale",
      "-11.02",
      ""
    ],
    "tags": null,
    "description": "Kindle Unltd*EL3SL17V3",
    "amount": -11.02
  },
  {
    "id": 17,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-04-28",
    "transaction_data": [
      "04/28/2023",
      "04/30/2023",
      "Alexa Skills*HM6350Z30",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "Alexa Skills*HM6350Z30",
    "amount": -0.88
  },
  {
    "id": 18,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-04-25",
    "transaction_data": [
      "04/25/2023",
      "04/25/2023",
      "ALEXA SKILLS*HF0K62JR2 AM",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "ALEXA SKILLS*HF0K62JR2 AM",
    "amount": -0.88
  },
  {
    "id": 19,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-04-24",
    "transaction_data": [
      "04/24/2023",
      "04/24/2023",
      "PURCHASE INTEREST CHARGE",
      "Fees & Adjustments",
      "Fee",
      "-165.72",
      ""
    ],
    "tags": null,
    "description": "PURCHASE INTEREST CHARGE",
    "amount": -165.72
  },
  {
    "id": 20,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-04-15",
    "transaction_data": [
      "04/15/2023",
      "04/16/2023",
      "Amazon Music*HJ67R1SM2",
      "Shopping",
      "Sale",
      "-17.64",
      ""
    ],
    "tags": null,
    "description": "Amazon Music*HJ67R1SM2",
    "amount": -17.64
  },
  {
    "id": 21,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-04-13",
    "transaction_data": [
      "04/13/2023",
      "04/13/2023",
      "Payment Thank You - Web",
      "",
      "Payment",
      "296.31",
      ""
    ],
    "tags": null,
    "description": "Payment Thank You - Web",
    "amount": 296.31
  },
  {
    "id": 22,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-04-02",
    "transaction_data": [
      "04/02/2023",
      "04/03/2023",
      "Kindle Unltd*HS6NR03K0",
      "Shopping",
      "Sale",
      "-11.02",
      ""
    ],
    "tags": null,
    "description": "Kindle Unltd*HS6NR03K0",
    "amount": -11.02
  },
  {
    "id": 23,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-31",
    "transaction_data": [
      "03/31/2023",
      "04/02/2023",
      "AMZN Mktp US*HY6VE2851",
      "Shopping",
      "Sale",
      "-197.99",
      ""
    ],
    "tags": null,
    "description": "AMZN Mktp US*HY6VE2851",
    "amount": -197.99
  },
  {
    "id": 24,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-31",
    "transaction_data": [
      "03/31/2023",
      "04/02/2023",
      "AMZN Mktp US*HY8040TS2",
      "Shopping",
      "Sale",
      "-102.84",
      ""
    ],
    "tags": null,
    "description": "AMZN Mktp US*HY8040TS2",
    "amount": -102.84
  },
  {
    "id": 25,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-28",
    "transaction_data": [
      "03/28/2023",
      "03/29/2023",
      "Alexa Skills*H72QZ4SZ2",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "Alexa Skills*H72QZ4SZ2",
    "amount": -0.88
  },
  {
    "id": 26,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-25",
    "transaction_data": [
      "03/25/2023",
      "03/26/2023",
      "ALEXA SKILLS*H72764TN2 AM",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "ALEXA SKILLS*H72764TN2 AM",
    "amount": -0.88
  },
  {
    "id": 27,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-24",
    "transaction_data": [
      "03/24/2023",
      "03/24/2023",
      "PURCHASE INTEREST CHARGE",
      "Fees & Adjustments",
      "Fee",
      "-148.30",
      ""
    ],
    "tags": null,
    "description": "PURCHASE INTEREST CHARGE",
    "amount": -148.3
  },
  {
    "id": 28,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-16",
    "transaction_data": [
      "03/16/2023",
      "03/17/2023",
      "AMZN Mktp US*HG0AR0YR2",
      "Shopping",
      "Sale",
      "-384.99",
      ""
    ],
    "tags": null,
    "description": "AMZN Mktp US*HG0AR0YR2",
    "amount": -384.99
  },
  {
    "id": 29,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-15",
    "transaction_data": [
      "03/15/2023",
      "03/16/2023",
      "Amazon Music*HC9NF1MW0",
      "Shopping",
      "Sale",
      "-17.64",
      ""
    ],
    "tags": null,
    "description": "Amazon Music*HC9NF1MW0",
    "amount": -17.64
  },
  {
    "id": 30,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-14",
    "transaction_data": [
      "03/14/2023",
      "03/14/2023",
      "Payment Thank You - Web",
      "",
      "Payment",
      "270.22",
      ""
    ],
    "tags": null,
    "description": "Payment Thank You - Web",
    "amount": 270.22
  },
  {
    "id": 31,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-02",
    "transaction_data": [
      "03/02/2023",
      "03/03/2023",
      "Kindle Unltd*H57G32GP0",
      "Shopping",
      "Sale",
      "-11.02",
      ""
    ],
    "tags": null,
    "description": "Kindle Unltd*H57G32GP0",
    "amount": -11.02
  },
  {
    "id": 32,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-03-01",
    "transaction_data": [
      "03/01/2023",
      "03/02/2023",
      "Amazon.com*H57KI23D0",
      "Shopping",
      "Sale",
      "-88.93",
      ""
    ],
    "tags": null,
    "description": "Amazon.com*H57KI23D0",
    "amount": -88.93
  },
  {
    "id": 33,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-28",
    "transaction_data": [
      "02/28/2023",
      "03/01/2023",
      "Alexa Skills*HD6950EJ2",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "Alexa Skills*HD6950EJ2",
    "amount": -0.88
  },
  {
    "id": 34,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-27",
    "transaction_data": [
      "02/27/2023",
      "02/28/2023",
      "WF WAYFAIR3869788846",
      "Home",
      "Sale",
      "-176.47",
      ""
    ],
    "tags": null,
    "description": "WF WAYFAIR3869788846",
    "amount": -176.47
  },
  {
    "id": 35,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-25",
    "transaction_data": [
      "02/25/2023",
      "02/26/2023",
      "Alexa Skills*HD8R62PV0",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "Alexa Skills*HD8R62PV0",
    "amount": -0.88
  },
  {
    "id": 36,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-24",
    "transaction_data": [
      "02/24/2023",
      "02/24/2023",
      "PURCHASE INTEREST CHARGE",
      "Fees & Adjustments",
      "Fee",
      "-157.03",
      ""
    ],
    "tags": null,
    "description": "PURCHASE INTEREST CHARGE",
    "amount": -157.03
  },
  {
    "id": 37,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-15",
    "transaction_data": [
      "02/15/2023",
      "02/16/2023",
      "Amazon Music*HP1YL14B0",
      "Shopping",
      "Sale",
      "-17.64",
      ""
    ],
    "tags": null,
    "description": "Amazon Music*HP1YL14B0",
    "amount": -17.64
  },
  {
    "id": 38,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-14",
    "transaction_data": [
      "02/14/2023",
      "02/15/2023",
      "Payment Thank You - Web",
      "",
      "Payment",
      "150.00",
      ""
    ],
    "tags": null,
    "description": "Payment Thank You - Web",
    "amount": 150
  },
  {
    "id": 39,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-07",
    "transaction_data": [
      "02/07/2023",
      "02/08/2023",
      "WF WAYFAIR3568935856",
      "Home",
      "Sale",
      "-579.03",
      ""
    ],
    "tags": null,
    "description": "WF WAYFAIR3568935856",
    "amount": -579.03
  },
  {
    "id": 40,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-02-02",
    "transaction_data": [
      "02/02/2023",
      "02/03/2023",
      "Kindle Unltd*PB9C96YR3",
      "Shopping",
      "Sale",
      "-11.02",
      ""
    ],
    "tags": null,
    "description": "Kindle Unltd*PB9C96YR3",
    "amount": -11.02
  },
  {
    "id": 41,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-31",
    "transaction_data": [
      "01/31/2023",
      "01/31/2023",
      "Payment Thank You - Web",
      "",
      "Payment",
      "150.00",
      ""
    ],
    "tags": null,
    "description": "Payment Thank You - Web",
    "amount": 150
  },
  {
    "id": 42,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-31",
    "transaction_data": [
      "01/31/2023",
      "01/31/2023",
      "Amazon.com*QQ8ZF6QG3",
      "Shopping",
      "Sale",
      "-30.37",
      ""
    ],
    "tags": null,
    "description": "Amazon.com*QQ8ZF6QG3",
    "amount": -30.37
  },
  {
    "id": 43,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-28",
    "transaction_data": [
      "01/28/2023",
      "01/29/2023",
      "Alexa Skills*DH8BW5KG3",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "Alexa Skills*DH8BW5KG3",
    "amount": -0.88
  },
  {
    "id": 44,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-25",
    "transaction_data": [
      "01/25/2023",
      "01/25/2023",
      "ALEXA SKILLS*DY07F7BL3 AM",
      "Shopping",
      "Sale",
      "-0.88",
      ""
    ],
    "tags": null,
    "description": "ALEXA SKILLS*DY07F7BL3 AM",
    "amount": -0.88
  },
  {
    "id": 45,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-24",
    "transaction_data": [
      "01/24/2023",
      "01/24/2023",
      "PURCHASE INTEREST CHARGE",
      "Fees & Adjustments",
      "Fee",
      "-147.22",
      ""
    ],
    "tags": null,
    "description": "PURCHASE INTEREST CHARGE",
    "amount": -147.22
  },
  {
    "id": 46,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-21",
    "transaction_data": [
      "01/21/2023",
      "01/22/2023",
      "PP *WWGOA.com Purchase",
      "Bills & Utilities",
      "Sale",
      "-79.42",
      ""
    ],
    "tags": null,
    "description": "PP *WWGOA.com Purchase",
    "amount": -79.42
  },
  {
    "id": 47,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-18",
    "transaction_data": [
      "01/18/2023",
      "01/18/2023",
      "AMZN Mktp US*9V2ZK5PW3",
      "Shopping",
      "Sale",
      "-134.54",
      ""
    ],
    "tags": null,
    "description": "AMZN Mktp US*9V2ZK5PW3",
    "amount": -134.54
  },
  {
    "id": 48,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-15",
    "transaction_data": [
      "01/15/2023",
      "01/16/2023",
      "Amazon Music*SN4AG6GX3",
      "Shopping",
      "Sale",
      "-17.64",
      ""
    ],
    "tags": null,
    "description": "Amazon Music*SN4AG6GX3",
    "amount": -17.64
  },
  {
    "id": 49,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-14",
    "transaction_data": [
      "01/14/2023",
      "01/15/2023",
      "AMZN Mktp US*8K2UY6W63",
      "Shopping",
      "Sale",
      "-27.41",
      ""
    ],
    "tags": null,
    "description": "AMZN Mktp US*8K2UY6W63",
    "amount": -27.41
  },
  {
    "id": 50,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-12",
    "transaction_data": [
      "01/12/2023",
      "01/12/2023",
      "Payment Thank You - Web",
      "",
      "Payment",
      "239.22",
      ""
    ],
    "tags": null,
    "description": "Payment Thank You - Web",
    "amount": 239.22
  },
  {
    "id": 51,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-10",
    "transaction_data": [
      "01/10/2023",
      "01/11/2023",
      "Amazon.com*6P0ES20T3",
      "Shopping",
      "Sale",
      "-23.56",
      ""
    ],
    "tags": null,
    "description": "Amazon.com*6P0ES20T3",
    "amount": -23.56
  },
  {
    "id": 52,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-02",
    "transaction_data": [
      "01/02/2023",
      "01/03/2023",
      "Kindle Unltd*E71AS39O3",
      "Shopping",
      "Sale",
      "-11.02",
      ""
    ],
    "tags": null,
    "description": "Kindle Unltd*E71AS39O3",
    "amount": -11.02
  },
  {
    "id": 53,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2023-01-02",
    "transaction_data": [
      "01/02/2023",
      "01/02/2023",
      "AMZN Mktp US*DN6L62PO3",
      "Shopping",
      "Sale",
      "-3.54",
      ""
    ],
    "tags": null,
    "description": "AMZN Mktp US*DN6L62PO3",
    "amount": -3.54
  },
  {
    "id": 54,
    "batch_id": 1,
    "institution_id": 4,
    "transaction_date": "2022-12-30",
    "transaction_data": [
      "12/30/2022",
      "01/01/2023",
      "AMZN Mktp US*2T0J28W63",
      "Shopping",
      "Sale",
      "-18.94",
      ""
    ],
    "tags": null,
    "description": "AMZN Mktp US*2T0J28W63",
    "amount": -18.94
  },
  {
    "id": 55,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-03",
    "transaction_data": [
      "01/03/2023",
      "14:31:36",
      "PST",
      "Uber Technologies, Inc",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-76.60",
      "0.00",
      "-76.60",
      "clacina@mindspring.com",
      "paypal-us@uber.com",
      "898381650L546364E",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "SCvVlV7ntwhCMncRKMevGa0",
      "",
      "1",
      "",
      "-76.60",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Technologies, Inc",
    "amount": -76.6
  },
  {
    "id": 56,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-03",
    "transaction_data": [
      "01/03/2023",
      "14:31:38",
      "PST",
      "Uber Technologies, Inc",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-15.00",
      "0.00",
      "-15.00",
      "clacina@mindspring.com",
      "paypal-us@uber.com",
      "9BD382381H696745A",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "115QGIoFWSfcGWfMQBTbCIa0",
      "",
      "1",
      "",
      "-15.00",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Technologies, Inc",
    "amount": -15
  },
  {
    "id": 57,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-05",
    "transaction_data": [
      "01/05/2023",
      "15:50:52",
      "PST",
      "Uber Eats",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-23.83",
      "0.00",
      "-23.83",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "04F80961P13761845",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "6LN68842EG207831E",
      "2q9UzTYntTANsrcwa083Osa0",
      "",
      "1",
      "",
      "-23.83",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -23.83
  },
  {
    "id": 58,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-05",
    "transaction_data": [
      "01/05/2023",
      "15:50:52",
      "PST",
      "Uber Eats",
      "General Authorization",
      "Completed",
      "USD",
      "-29.31",
      "0.00",
      "-29.31",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "6LN68842EG207831E",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "2q9UzTYntTANsrcwa083Osa0",
      "",
      "1",
      "",
      "0.00",
      "",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -29.31
  },
  {
    "id": 59,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-05",
    "transaction_data": [
      "01/05/2023",
      "16:45:29",
      "PST",
      "Unity Technologies ApS",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-9.93",
      "0.00",
      "-9.93",
      "clacina@mindspring.com",
      "payments@unity3d.com",
      "10V76286JE756132T",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-22006058N5665462B",
      "2474893001791",
      "",
      "1",
      "",
      "-9.93",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Unity Technologies ApS",
    "amount": -9.93
  },
  {
    "id": 60,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-05",
    "transaction_data": [
      "01/05/2023",
      "16:50:52",
      "PST",
      "Uber Eats",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-5.48",
      "0.00",
      "-5.48",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "09J698840A544391A",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "1BBawgLJ3k1jOA6gMdfpPea0",
      "",
      "1",
      "",
      "-5.48",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -5.48
  },
  {
    "id": 61,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-06",
    "transaction_data": [
      "01/06/2023",
      "08:22:18",
      "PST",
      "Ten Digital Pte. Ltd.",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-57.96",
      "0.00",
      "-57.96",
      "clacina@mindspring.com",
      "paypal@tendc.co",
      "9ML149244L088130E",
      "Octopus - Wooden Jigsaw Puzzle - A3/Big, Mother Earth - Wooden Jigsaw Puzzle - A3/Big, Elephant - Wooden Jigsaw Puzzle - A3/Big, Rainbow Lion - Wooden Jigsaw Puzzle - A3/Big",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "c26423865540814.1",
      "Shopify",
      "4",
      "",
      "-57.96",
      "Octopus - Wooden Jigsaw Puzzle - A3/BigMother Earth - Wooden Jigsaw Puzzle - A3/BigElephant - Wooden Jigsaw Puzzle - A3/BigRainbow Lion - Wooden Jigsaw Puzzle - A3/Big",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Ten Digital Pte. Ltd.",
    "amount": -57.96
  },
  {
    "id": 62,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-06",
    "transaction_data": [
      "01/06/2023",
      "12:02:25",
      "PST",
      "Uber Technologies, Inc",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-53.69",
      "0.00",
      "-53.69",
      "clacina@mindspring.com",
      "paypal-us@uber.com",
      "2NR08163059191108",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "8KY103499V839304J",
      "6OJvXt9QJ5Cfnvb6jhgTHXa0",
      "",
      "1",
      "",
      "-53.69",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Technologies, Inc",
    "amount": -53.69
  },
  {
    "id": 63,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-06",
    "transaction_data": [
      "01/06/2023",
      "12:02:25",
      "PST",
      "Uber Technologies, Inc",
      "General Authorization",
      "Completed",
      "USD",
      "-53.69",
      "0.00",
      "-53.69",
      "clacina@mindspring.com",
      "paypal-us@uber.com",
      "8KY103499V839304J",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "6OJvXt9QJ5Cfnvb6jhgTHXa0",
      "",
      "1",
      "",
      "0.00",
      "",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "Uber Technologies, Inc",
    "amount": -53.69
  },
  {
    "id": 64,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-10",
    "transaction_data": [
      "01/10/2023",
      "18:16:35",
      "PST",
      "1&1 IONOS Inc.",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-15.00",
      "0.00",
      "-15.00",
      "clacina@mindspring.com",
      "paypal@1and1.com",
      "67Y121832F936034R",
      "K651887266/005079584824",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-6UV73398DV573131S",
      "K651887266/005079584824",
      "",
      "1",
      "",
      "-15.00",
      "K651887266/005079584824",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "1&1 IONOS Inc.",
    "amount": -15
  },
  {
    "id": 65,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-14",
    "transaction_data": [
      "01/14/2023",
      "02:48:44",
      "PST",
      "GameDevHQ, Inc.",
      "Subscription Payment",
      "Completed",
      "USD",
      "-99.00",
      "0.00",
      "-99.00",
      "clacina@mindspring.com",
      "subscriptions@gamedevhq.com",
      "13286162MP432200N",
      "PRO YEARLY at GameDevHQ",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "I-6BRC4PXDNRLF",
      "",
      "",
      "1",
      "",
      "-99.00",
      "PRO YEARLY at GameDevHQ",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "GameDevHQ, Inc.",
    "amount": -99
  },
  {
    "id": 66,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-17",
    "transaction_data": [
      "01/17/2023",
      "09:02:19",
      "PST",
      "FastSpring",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-17.65",
      "0.00",
      "-17.65",
      "clacina@mindspring.com",
      "pporders@fastspring.com",
      "905264290D364554D",
      "Bartender 4",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "2Y145435TR9266404",
      "",
      "",
      "1",
      "",
      "-17.65",
      "Bartender 4",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "FastSpring",
    "amount": -17.65
  },
  {
    "id": 67,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-17",
    "transaction_data": [
      "01/17/2023",
      "09:02:19",
      "PST",
      "FastSpring",
      "General Authorization",
      "Completed",
      "USD",
      "-17.65",
      "0.00",
      "-17.65",
      "clacina@mindspring.com",
      "pporders@fastspring.com",
      "2Y145435TR9266404",
      "Bartender 4",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "1",
      "",
      "0.00",
      "Bartender 4",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "FastSpring",
    "amount": -17.65
  },
  {
    "id": 68,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-21",
    "transaction_data": [
      "01/21/2023",
      "07:13:10",
      "PST",
      "SQ *GO PHILLY LAKEWOOD",
      "Website Payment",
      "Completed",
      "USD",
      "-20.00",
      "0.00",
      "-20.00",
      "clacina@mindspring.com",
      "",
      "57766387N8170803C",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "36E9977667744192B",
      "",
      "",
      "",
      "",
      "-20.00",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "SQ *GO PHILLY LAKEWOOD",
    "amount": -20
  },
  {
    "id": 69,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-21",
    "transaction_data": [
      "01/21/2023",
      "07:13:10",
      "PST",
      "SQ *GO PHILLY LAKEWOOD",
      "General Authorization",
      "Completed",
      "USD",
      "-20.00",
      "0.00",
      "-20.00",
      "clacina@mindspring.com",
      "",
      "36E9977667744192B",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "0.00",
      "",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "SQ *GO PHILLY LAKEWOOD",
    "amount": -20
  },
  {
    "id": 70,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-23",
    "transaction_data": [
      "01/23/2023",
      "13:50:43",
      "PST",
      "Uber Eats",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-27.67",
      "0.00",
      "-27.67",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "31937795YF918852W",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "53B552299L723444B",
      "7HOnWumC3tIUvWWKPMD76a0",
      "",
      "1",
      "",
      "-27.67",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -27.67
  },
  {
    "id": 109,
    "batch_id": 1,
    "institution_id": 5,
    "transaction_date": "2023-01-12",
    "transaction_data": [
      "01/12/2023",
      "\t$-200.00",
      "\tONLINE PAYMENT        DEERFIELD    IL\t",
      "payment"
    ],
    "tags": null,
    "description": "payment",
    "amount": -200
  },
  {
    "id": 71,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-23",
    "transaction_data": [
      "01/23/2023",
      "13:50:43",
      "PST",
      "Uber Eats",
      "General Authorization",
      "Completed",
      "USD",
      "-32.67",
      "0.00",
      "-32.67",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "53B552299L723444B",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "7HOnWumC3tIUvWWKPMD76a0",
      "",
      "1",
      "",
      "0.00",
      "",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -32.67
  },
  {
    "id": 72,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-23",
    "transaction_data": [
      "01/23/2023",
      "14:50:42",
      "PST",
      "Uber Eats",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-5.00",
      "0.00",
      "-5.00",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "3DN96580JU473402W",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "3snGjcxVcviU3ma4ESOLvma0",
      "",
      "1",
      "",
      "-5.00",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -5
  },
  {
    "id": 73,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-29",
    "transaction_data": [
      "01/29/2023",
      "14:09:07",
      "PST",
      "Uber Eats",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-24.87",
      "0.00",
      "-24.87",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "4EN47189R8894370C",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "1CX84490NJ579950A",
      "kibe1kfogWkBxEp7CyT4Qa0",
      "",
      "1",
      "",
      "-24.87",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -24.87
  },
  {
    "id": 74,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-29",
    "transaction_data": [
      "01/29/2023",
      "14:09:07",
      "PST",
      "Uber Eats",
      "General Authorization",
      "Completed",
      "USD",
      "-30.56",
      "0.00",
      "-30.56",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "1CX84490NJ579950A",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "kibe1kfogWkBxEp7CyT4Qa0",
      "",
      "1",
      "",
      "0.00",
      "",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -30.56
  },
  {
    "id": 75,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-29",
    "transaction_data": [
      "01/29/2023",
      "15:09:06",
      "PST",
      "Uber Eats",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-5.69",
      "0.00",
      "-5.69",
      "clacina@mindspring.com",
      "paypal-us-eats-group@uber.com",
      "10Y14528KT4834746",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-34X4798607464050W",
      "2zVpEeJfYteCe6iAWyccpRa0",
      "",
      "1",
      "",
      "-5.69",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Uber Eats",
    "amount": -5.69
  },
  {
    "id": 76,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-01-31",
    "transaction_data": [
      "01/31/2023",
      "09:57:47",
      "PST",
      "PayPal Cashback Mastercard",
      "General Payment",
      "Completed",
      "USD",
      "-200.00",
      "0.00",
      "-200.00",
      "clacina@mindspring.com",
      "",
      "0FG14778499170619",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "-200.00",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "PayPal Cashback Mastercard",
    "amount": -200
  },
  {
    "id": 77,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-03",
    "transaction_data": [
      "02/03/2023",
      "09:11:04",
      "PST",
      "Ticketmaster, LLC",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-535.85",
      "0.00",
      "-535.85",
      "clacina@mindspring.com",
      "TMpaypal001@ticketmaster.com",
      "2VS66822LB780634W",
      "TM *TICKETMASTER",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "SEA/58-21178",
      "",
      "1",
      "",
      "-535.85",
      "TM *TICKETMASTER",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Ticketmaster, LLC",
    "amount": -535.85
  },
  {
    "id": 78,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-05",
    "transaction_data": [
      "02/05/2023",
      "16:45:17",
      "PST",
      "Unity Technologies ApS",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-9.93",
      "0.00",
      "-9.93",
      "clacina@mindspring.com",
      "payments@unity3d.com",
      "0R48495439185172M",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-22006058N5665462B",
      "2474921414498",
      "",
      "1",
      "",
      "-9.93",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Unity Technologies ApS",
    "amount": -9.93
  },
  {
    "id": 79,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-10",
    "transaction_data": [
      "02/10/2023",
      "16:16:06",
      "PST",
      "1&1 IONOS Inc.",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-55.00",
      "0.00",
      "-55.00",
      "clacina@mindspring.com",
      "paypal@1and1.com",
      "0D990021A9557054P",
      "K651887266/005299058323",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-6UV73398DV573131S",
      "K651887266/005299058323",
      "",
      "1",
      "",
      "-55.00",
      "K651887266/005299058323",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "1&1 IONOS Inc.",
    "amount": -55
  },
  {
    "id": 80,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-11",
    "transaction_data": [
      "02/11/2023",
      "02:22:57",
      "PST",
      "Sew Essential",
      "Subscription Payment",
      "Completed",
      "USD",
      "-12.75",
      "0.00",
      "-12.75",
      "clacina@mindspring.com",
      "silk@sew-essential.com",
      "2M9433488C910735C",
      "Yearly Subscription",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "I-HV28W1M7JRNA",
      "",
      "",
      "1",
      "",
      "-12.75",
      "Yearly Subscription",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Sew Essential",
    "amount": -12.75
  },
  {
    "id": 81,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-14",
    "transaction_data": [
      "02/14/2023",
      "05:17:26",
      "PST",
      "ALIPAY US, INC.",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-52.03",
      "0.00",
      "-52.03",
      "clacina@mindspring.com",
      "AE-AlipayUSPaypal@service.alibaba.com",
      "6GA85845XM4928444",
      "185W Led Garage Light with Plug 18000LM Lamp Adjustable Deformable Bulb Ceiling Light for Storage/Warehouse Workshop Lighting",
      "8162446564099513",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "2023021481031300001068840124456",
      "AE_US_USD",
      "1",
      "",
      "-52.03",
      "12990501203230214066396859513",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "ALIPAY US, INC.",
    "amount": -52.03
  },
  {
    "id": 82,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-20",
    "transaction_data": [
      "02/20/2023",
      "09:09:13",
      "PST",
      "Hostwinds",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-4.99",
      "0.00",
      "-4.99",
      "clacina@mindspring.com",
      "payments@hostwinds.com",
      "81H53333A7769312L",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-48P190783J1010028",
      "3070430",
      "",
      "1",
      "",
      "-4.99",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Hostwinds",
    "amount": -4.99
  },
  {
    "id": 83,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-21",
    "transaction_data": [
      "02/21/2023",
      "17:27:14",
      "PST",
      "Udemy",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-18.74",
      "0.00",
      "-18.74",
      "clacina@mindspring.com",
      "payments@udemy.com",
      "40J72745H5539862U",
      "course:1565838",
      "",
      "1.75",
      "",
      "",
      "",
      "",
      "",
      "",
      "290445212",
      "1",
      "",
      "-18.74",
      "The Complete 2023 Web Development Bootcamp",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Udemy",
    "amount": -18.74
  },
  {
    "id": 84,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-23",
    "transaction_data": [
      "02/23/2023",
      "13:53:17",
      "PST",
      "PayPal Cashback Mastercard",
      "General Payment",
      "Completed",
      "USD",
      "-200.00",
      "0.00",
      "-200.00",
      "clacina@mindspring.com",
      "",
      "21312611H8192622R",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "-200.00",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "PayPal Cashback Mastercard",
    "amount": -200
  },
  {
    "id": 85,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-02-26",
    "transaction_data": [
      "02/26/2023",
      "02:08:21",
      "PST",
      "ALIPAY US, INC.",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-19.28",
      "0.00",
      "-19.28",
      "clacina@mindspring.com",
      "AE-AlipayUSPaypal@service.alibaba.com",
      "39V86892983233143",
      "Butterfly Night Lights Pasteable 3D Butterfly Wall Stickers Lamps 1/5PCS Home Decoration DIY Living Room Wall Sticker Lighting",
      "8163106350169513",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "2023022681031300001065240438497",
      "AE_US_USD",
      "1",
      "",
      "-19.28",
      "12990501203230226593801919513",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "ALIPAY US, INC.",
    "amount": -19.28
  },
  {
    "id": 86,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-01",
    "transaction_data": [
      "03/01/2023",
      "04:48:59",
      "PST",
      "eBay Commerce Inc.",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-29.46",
      "0.00",
      "-29.46",
      "clacina@mindspring.com",
      "ECI_USD_PPFOP@ebay.com",
      "8AE90512PJ3107613",
      "Purchase amount",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "1XK45311BE830613C",
      "v2_e5c2e5c9-e7d4-444a-84b4-292cdee05fbc_2_20",
      "100022545663805",
      "1",
      "",
      "-29.46",
      "Purchase amount",
      "Order Number : 17-09763-08491",
      "Debit"
    ],
    "tags": null,
    "description": "eBay Commerce Inc.",
    "amount": -29.46
  },
  {
    "id": 87,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-01",
    "transaction_data": [
      "03/01/2023",
      "04:48:59",
      "PST",
      "eBay Commerce Inc.",
      "General Authorization",
      "Completed",
      "USD",
      "-29.46",
      "0.00",
      "-29.46",
      "clacina@mindspring.com",
      "ECI_USD_PPFOP@ebay.com",
      "1XK45311BE830613C",
      "Purchase amount",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "9ffec0f9-2138-4150-b493-cf8f7a8aff1e",
      "100022545663805",
      "1",
      "",
      "0.00",
      "Purchase amount",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "eBay Commerce Inc.",
    "amount": -29.46
  },
  {
    "id": 88,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-01",
    "transaction_data": [
      "03/01/2023",
      "09:07:50",
      "PST",
      "Hostwinds",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-0.92",
      "0.00",
      "-0.92",
      "clacina@mindspring.com",
      "payments@hostwinds.com",
      "4NV70542RR4320252",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-48P190783J1010028",
      "3095802",
      "",
      "1",
      "",
      "-0.92",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Hostwinds",
    "amount": -0.92
  },
  {
    "id": 89,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-01",
    "transaction_data": [
      "03/01/2023",
      "18:35:13",
      "PST",
      "eBay Commerce Inc.",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-32.95",
      "0.00",
      "-32.95",
      "clacina@mindspring.com",
      "ECI_USD_PPFOP@ebay.com",
      "42C10631PU8802429",
      "Purchase amount",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "1HX45605PL835722G",
      "v2_8f5264b4-5d51-40f6-a4ba-83290434381a_2_8",
      "100022553843395",
      "1",
      "",
      "-32.95",
      "Purchase amount",
      "Order Number : 08-09769-99123",
      "Debit"
    ],
    "tags": null,
    "description": "eBay Commerce Inc.",
    "amount": -32.95
  },
  {
    "id": 90,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-01",
    "transaction_data": [
      "03/01/2023",
      "18:35:13",
      "PST",
      "eBay Commerce Inc.",
      "General Authorization",
      "Completed",
      "USD",
      "-32.95",
      "0.00",
      "-32.95",
      "clacina@mindspring.com",
      "ECI_USD_PPFOP@ebay.com",
      "1HX45605PL835722G",
      "Purchase amount",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "5de4888f-1723-4b0d-a0cf-ff9a728e4f9f",
      "100022553843395",
      "1",
      "",
      "0.00",
      "Purchase amount",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "eBay Commerce Inc.",
    "amount": -32.95
  },
  {
    "id": 91,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-05",
    "transaction_data": [
      "03/05/2023",
      "16:48:14",
      "PST",
      "Unity Technologies ApS",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-9.93",
      "0.00",
      "-9.93",
      "clacina@mindspring.com",
      "payments@unity3d.com",
      "8NJ107887S2004135",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-22006058N5665462B",
      "2474951110771",
      "",
      "1",
      "",
      "-9.93",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Unity Technologies ApS",
    "amount": -9.93
  },
  {
    "id": 92,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-06",
    "transaction_data": [
      "03/06/2023",
      "12:34:44",
      "PST",
      "Udemy",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-14.33",
      "0.00",
      "-14.33",
      "clacina@mindspring.com",
      "payments@udemy.com",
      "6AT54470H5253413J",
      "course:3656160",
      "",
      "1.34",
      "",
      "",
      "",
      "",
      "",
      "",
      "292343312",
      "1",
      "",
      "-14.33",
      "Basic Home Electrical Wiring by Example and On the Job",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Udemy",
    "amount": -14.33
  },
  {
    "id": 93,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-14",
    "transaction_data": [
      "03/14/2023",
      "09:09:19",
      "PDT",
      "eBay Commerce Inc.",
      "Express Checkout Payment",
      "Completed",
      "USD",
      "-60.50",
      "0.00",
      "-60.50",
      "clacina@mindspring.com",
      "ECI_USD_PPFOP@ebay.com",
      "4EH87335VF552131B",
      "Purchase amount",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "76H4199484604122H",
      "v2_1a061bd2-95c1-42b0-91e0-e38c83598a33_2_16",
      "100022629173532",
      "1",
      "",
      "-60.50",
      "Purchase amount",
      "Order Number : 06-09822-57083",
      "Debit"
    ],
    "tags": null,
    "description": "eBay Commerce Inc.",
    "amount": -60.5
  },
  {
    "id": 94,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-14",
    "transaction_data": [
      "03/14/2023",
      "09:09:19",
      "PDT",
      "eBay Commerce Inc.",
      "General Authorization",
      "Completed",
      "USD",
      "-60.50",
      "0.00",
      "-60.50",
      "clacina@mindspring.com",
      "ECI_USD_PPFOP@ebay.com",
      "76H4199484604122H",
      "Purchase amount",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "",
      "1d8d9237-fe3b-4b2d-b94d-bf67b99d37da",
      "100022629173532",
      "1",
      "",
      "0.00",
      "Purchase amount",
      "",
      "Memo"
    ],
    "tags": null,
    "description": "eBay Commerce Inc.",
    "amount": -60.5
  },
  {
    "id": 95,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-19",
    "transaction_data": [
      "03/19/2023",
      "10:16:31",
      "PDT",
      "Hostwinds",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-4.99",
      "0.00",
      "-4.99",
      "clacina@mindspring.com",
      "payments@hostwinds.com",
      "9M881629KM3669814",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-48P190783J1010028",
      "3099847",
      "",
      "1",
      "",
      "-4.99",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Hostwinds",
    "amount": -4.99
  },
  {
    "id": 96,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-20",
    "transaction_data": [
      "03/20/2023",
      "17:33:01",
      "PDT",
      "1&1 IONOS Inc.",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-17.00",
      "0.00",
      "-17.00",
      "clacina@mindspring.com",
      "paypal@1and1.com",
      "09831424L22833306",
      "K651887266/005468592277",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-6UV73398DV573131S",
      "K651887266/005468592277",
      "",
      "1",
      "",
      "-17.00",
      "K651887266/005468592277",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "1&1 IONOS Inc.",
    "amount": -17
  },
  {
    "id": 97,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-24",
    "transaction_data": [
      "03/24/2023",
      "14:08:04",
      "PDT",
      "Valve Corp.",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-33.08",
      "0.00",
      "-33.08",
      "clacina@mindspring.com",
      "steamgames@steampowered.com",
      "88599215WN3823415",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-6M848057S0390314W",
      "3600104981461362454",
      "",
      "1",
      "",
      "-33.08",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Valve Corp.",
    "amount": -33.08
  },
  {
    "id": 98,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-03-31",
    "transaction_data": [
      "03/31/2023",
      "17:28:22",
      "PDT",
      "Paddle.com Market Limited",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-34.95",
      "0.00",
      "-34.95",
      "clacina@mindspring.com",
      "payments@paddle.com",
      "9M867600W88995058",
      "CleanMyMac X - 1 Year",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-9MJ51597D3714143S",
      "",
      "",
      "1",
      "",
      "-34.95",
      "CleanMyMac X - 1 Year",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Paddle.com Market Limited",
    "amount": -34.95
  },
  {
    "id": 99,
    "batch_id": 1,
    "institution_id": 6,
    "transaction_date": "2023-04-01",
    "transaction_data": [
      "04/01/2023",
      "09:08:12",
      "PDT",
      "Hostwinds",
      "PreApproved Payment Bill User Payment",
      "Completed",
      "USD",
      "-1.02",
      "0.00",
      "-1.02",
      "clacina@mindspring.com",
      "payments@hostwinds.com",
      "9HV67519E1413792J",
      "",
      "",
      "0.00",
      "",
      "",
      "",
      "",
      "B-48P190783J1010028",
      "3126775",
      "",
      "1",
      "",
      "-1.02",
      "",
      "",
      "Debit"
    ],
    "tags": null,
    "description": "Hostwinds",
    "amount": -1.02
  }
];

export const transaction_data_descriptions = [
    {
        "id": 1,
        "institution_id": 3,
        "column_number": 0,
        "column_name": "Transaction Date",
        "column_type": "Date"
    },
    {
        "id": 2,
        "institution_id": 3,
        "column_number": 1,
        "column_name": "Posted Date",
        "column_type": "Date"
    },
    {
        "id": 3,
        "institution_id": 3,
        "column_number": 2,
        "column_name": "Card No",
        "column_type": "Number"
    },
    {
        "id": 4,
        "institution_id": 3,
        "column_number": 3,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 5,
        "institution_id": 3,
        "column_number": 4,
        "column_name": "Category",
        "column_type": "String"
    },
    {
        "id": 6,
        "institution_id": 3,
        "column_number": 5,
        "column_name": "Debit",
        "column_type": "Currency"
    },
    {
        "id": 7,
        "institution_id": 3,
        "column_number": 6,
        "column_name": "Credit",
        "column_type": "Currency"
    },
    {
        "id": 8,
        "institution_id": 11,
        "column_number": 0,
        "column_name": "Date",
        "column_type": "Date"
    },
    {
        "id": 9,
        "institution_id": 11,
        "column_number": 1,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 10,
        "institution_id": 11,
        "column_number": 2,
        "column_name": "Original Description",
        "column_type": "String"
    },
    {
        "id": 11,
        "institution_id": 11,
        "column_number": 3,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 12,
        "institution_id": 11,
        "column_number": 4,
        "column_name": "Transaction Type",
        "column_type": "String"
    },
    {
        "id": 13,
        "institution_id": 11,
        "column_number": 5,
        "column_name": "Category",
        "column_type": "String"
    },
    {
        "id": 14,
        "institution_id": 11,
        "column_number": 6,
        "column_name": "Account Name",
        "column_type": "String"
    },
    {
        "id": 15,
        "institution_id": 11,
        "column_number": 7,
        "column_name": "Labels",
        "column_type": "String"
    },
    {
        "id": 16,
        "institution_id": 11,
        "column_number": 8,
        "column_name": "Notes",
        "column_type": "String"
    },
    {
        "id": 17,
        "institution_id": 4,
        "column_number": 0,
        "column_name": "Transaction Date",
        "column_type": "Date"
    },
    {
        "id": 18,
        "institution_id": 4,
        "column_number": 1,
        "column_name": "Post Date",
        "column_type": "Date"
    },
    {
        "id": 19,
        "institution_id": 4,
        "column_number": 2,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 20,
        "institution_id": 4,
        "column_number": 3,
        "column_name": "Category",
        "column_type": "String"
    },
    {
        "id": 21,
        "institution_id": 4,
        "column_number": 4,
        "column_name": "Type",
        "column_type": "String"
    },
    {
        "id": 22,
        "institution_id": 4,
        "column_number": 5,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 23,
        "institution_id": 4,
        "column_number": 6,
        "column_name": "Memo",
        "column_type": "String"
    },
    {
        "id": 24,
        "institution_id": 5,
        "column_number": 0,
        "column_name": "Transaction Date",
        "column_type": "Date"
    },
    {
        "id": 25,
        "institution_id": 5,
        "column_number": 1,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 26,
        "institution_id": 5,
        "column_number": 2,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 27,
        "institution_id": 5,
        "column_number": 3,
        "column_name": "Type",
        "column_type": "String"
    },
    {
        "id": 28,
        "institution_id": 8,
        "column_number": 0,
        "column_name": "Date",
        "column_type": "Date"
    },
    {
        "id": 29,
        "institution_id": 8,
        "column_number": 1,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 30,
        "institution_id": 8,
        "column_number": 2,
        "column_name": "Original Description",
        "column_type": "String"
    },
    {
        "id": 31,
        "institution_id": 8,
        "column_number": 3,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 32,
        "institution_id": 8,
        "column_number": 4,
        "column_name": "Transaction Type",
        "column_type": "String"
    },
    {
        "id": 33,
        "institution_id": 8,
        "column_number": 5,
        "column_name": "Category",
        "column_type": "String"
    },
    {
        "id": 34,
        "institution_id": 8,
        "column_number": 6,
        "column_name": "Account Name",
        "column_type": "String"
    },
    {
        "id": 35,
        "institution_id": 8,
        "column_number": 7,
        "column_name": "Labels",
        "column_type": "String"
    },
    {
        "id": 36,
        "institution_id": 8,
        "column_number": 8,
        "column_name": "Notes",
        "column_type": "String"
    },
    {
        "id": 37,
        "institution_id": 9,
        "column_number": 0,
        "column_name": "Date",
        "column_type": "Date"
    },
    {
        "id": 38,
        "institution_id": 9,
        "column_number": 1,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 39,
        "institution_id": 9,
        "column_number": 2,
        "column_name": "Original Description",
        "column_type": "String"
    },
    {
        "id": 40,
        "institution_id": 9,
        "column_number": 3,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 41,
        "institution_id": 9,
        "column_number": 4,
        "column_name": "Transaction Type",
        "column_type": "String"
    },
    {
        "id": 42,
        "institution_id": 9,
        "column_number": 5,
        "column_name": "Category",
        "column_type": "String"
    },
    {
        "id": 43,
        "institution_id": 9,
        "column_number": 6,
        "column_name": "Account Name",
        "column_type": "String"
    },
    {
        "id": 44,
        "institution_id": 9,
        "column_number": 7,
        "column_name": "Labels",
        "column_type": "String"
    },
    {
        "id": 45,
        "institution_id": 9,
        "column_number": 8,
        "column_name": "Notes",
        "column_type": "String"
    },
    {
        "id": 46,
        "institution_id": 10,
        "column_number": 0,
        "column_name": "Date",
        "column_type": "Date"
    },
    {
        "id": 47,
        "institution_id": 10,
        "column_number": 1,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 48,
        "institution_id": 10,
        "column_number": 2,
        "column_name": "Original Description",
        "column_type": "String"
    },
    {
        "id": 49,
        "institution_id": 10,
        "column_number": 3,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 50,
        "institution_id": 10,
        "column_number": 4,
        "column_name": "Transaction Type",
        "column_type": "String"
    },
    {
        "id": 51,
        "institution_id": 10,
        "column_number": 5,
        "column_name": "Category",
        "column_type": "String"
    },
    {
        "id": 52,
        "institution_id": 10,
        "column_number": 6,
        "column_name": "Account Name",
        "column_type": "String"
    },
    {
        "id": 53,
        "institution_id": 10,
        "column_number": 7,
        "column_name": "Labels",
        "column_type": "String"
    },
    {
        "id": 54,
        "institution_id": 10,
        "column_number": 8,
        "column_name": "Notes",
        "column_type": "String"
    },
    {
        "id": 55,
        "institution_id": 1,
        "column_number": 0,
        "column_name": "Date",
        "column_type": "Date"
    },
    {
        "id": 56,
        "institution_id": 1,
        "column_number": 1,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 57,
        "institution_id": 1,
        "column_number": 2,
        "column_name": "Unused 1",
        "column_type": "String"
    },
    {
        "id": 58,
        "institution_id": 1,
        "column_number": 3,
        "column_name": "Unused 2",
        "column_type": "String"
    },
    {
        "id": 59,
        "institution_id": 1,
        "column_number": 4,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 60,
        "institution_id": 2,
        "column_number": 0,
        "column_name": "Date",
        "column_type": "Date"
    },
    {
        "id": 61,
        "institution_id": 2,
        "column_number": 1,
        "column_name": "Amount",
        "column_type": "Currency"
    },
    {
        "id": 62,
        "institution_id": 2,
        "column_number": 2,
        "column_name": "Unused 1",
        "column_type": "String"
    },
    {
        "id": 63,
        "institution_id": 2,
        "column_number": 3,
        "column_name": "Unused 2",
        "column_type": "String"
    },
    {
        "id": 64,
        "institution_id": 2,
        "column_number": 4,
        "column_name": "Description",
        "column_type": "String"
    },
    {
        "id": 65,
        "institution_id": 12,
        "column_number": 0,
        "column_name": "Website",
        "column_type": "String"
    },
    {
        "id": 66,
        "institution_id": 12,
        "column_number": 1,
        "column_name": "Order ID",
        "column_type": "String"
    },
    {
        "id": 67,
        "institution_id": 12,
        "column_number": 2,
        "column_name": "Order Date",
        "column_type": "Date"
    },
    {
        "id": 68,
        "institution_id": 12,
        "column_number": 3,
        "column_name": "Purchase Order Number",
        "column_type": "String"
    },
    {
        "id": 69,
        "institution_id": 12,
        "column_number": 4,
        "column_name": "Currency",
        "column_type": "String"
    },
    {
        "id": 70,
        "institution_id": 12,
        "column_number": 5,
        "column_name": "Unit Price",
        "column_type": "Currency"
    },
    {
        "id": 71,
        "institution_id": 12,
        "column_number": 6,
        "column_name": "Unit Price Tax",
        "column_type": "String"
    },
    {
        "id": 72,
        "institution_id": 12,
        "column_number": 7,
        "column_name": "Shipping Charge",
        "column_type": "String"
    },
    {
        "id": 73,
        "institution_id": 12,
        "column_number": 8,
        "column_name": "Total Discounts",
        "column_type": "String"
    },
    {
        "id": 74,
        "institution_id": 12,
        "column_number": 9,
        "column_name": "Total Owed",
        "column_type": "String"
    },
    {
        "id": 75,
        "institution_id": 12,
        "column_number": 10,
        "column_name": "Shipment Item Subtotal",
        "column_type": "String"
    },
    {
        "id": 76,
        "institution_id": 12,
        "column_number": 11,
        "column_name": "Shipment Item Subtotal Tax",
        "column_type": "String"
    },
    {
        "id": 77,
        "institution_id": 12,
        "column_number": 12,
        "column_name": "ASIN",
        "column_type": "String"
    },
    {
        "id": 78,
        "institution_id": 12,
        "column_number": 13,
        "column_name": "Product Condition",
        "column_type": "String"
    },
    {
        "id": 79,
        "institution_id": 12,
        "column_number": 14,
        "column_name": "Quantity",
        "column_type": "String"
    },
    {
        "id": 80,
        "institution_id": 12,
        "column_number": 15,
        "column_name": "Payment Instrument Type",
        "column_type": "String"
    },
    {
        "id": 81,
        "institution_id": 12,
        "column_number": 16,
        "column_name": "Order Status",
        "column_type": "String"
    },
    {
        "id": 82,
        "institution_id": 12,
        "column_number": 17,
        "column_name": "Shipment Status",
        "column_type": "String"
    },
    {
        "id": 83,
        "institution_id": 12,
        "column_number": 18,
        "column_name": "Ship Date",
        "column_type": "String"
    },
    {
        "id": 84,
        "institution_id": 12,
        "column_number": 19,
        "column_name": "Shipping Option",
        "column_type": "String"
    },
    {
        "id": 85,
        "institution_id": 12,
        "column_number": 20,
        "column_name": "Shipping Address",
        "column_type": "String"
    },
    {
        "id": 86,
        "institution_id": 12,
        "column_number": 21,
        "column_name": "Billing Address",
        "column_type": "String"
    },
    {
        "id": 87,
        "institution_id": 12,
        "column_number": 22,
        "column_name": "Carrier Name & Tracking Number",
        "column_type": "String"
    },
    {
        "id": 88,
        "institution_id": 12,
        "column_number": 23,
        "column_name": "Product Name",
        "column_type": "String"
    },
    {
        "id": 89,
        "institution_id": 12,
        "column_number": 24,
        "column_name": "Gift Message",
        "column_type": "String"
    },
    {
        "id": 90,
        "institution_id": 12,
        "column_number": 25,
        "column_name": "Gift Sender Name",
        "column_type": "String"
    },
    {
        "id": 91,
        "institution_id": 12,
        "column_number": 26,
        "column_name": "Gift Recipient Contact Details",
        "column_type": "String"
    },
    {
        "id": 92,
        "institution_id": 6,
        "column_number": 0,
        "column_name": "Date",
        "column_type": "Date"
    },
    {
        "id": 93,
        "institution_id": 6,
        "column_number": 1,
        "column_name": "Time",
        "column_type": "String"
    },
    {
        "id": 94,
        "institution_id": 6,
        "column_number": 2,
        "column_name": "TimeZone",
        "column_type": "String"
    },
    {
        "id": 95,
        "institution_id": 6,
        "column_number": 3,
        "column_name": "Name",
        "column_type": "String"
    },
    {
        "id": 96,
        "institution_id": 6,
        "column_number": 4,
        "column_name": "Type",
        "column_type": "String"
    },
    {
        "id": 97,
        "institution_id": 6,
        "column_number": 5,
        "column_name": "Status",
        "column_type": "String"
    },
    {
        "id": 98,
        "institution_id": 6,
        "column_number": 6,
        "column_name": "Currency",
        "column_type": "String"
    },
    {
        "id": 99,
        "institution_id": 6,
        "column_number": 7,
        "column_name": "Gross",
        "column_type": "Currency"
    },
    {
        "id": 100,
        "institution_id": 6,
        "column_number": 8,
        "column_name": "Fee",
        "column_type": "String"
    },
    {
        "id": 101,
        "institution_id": 6,
        "column_number": 9,
        "column_name": "Net",
        "column_type": "String"
    },
    {
        "id": 102,
        "institution_id": 6,
        "column_number": 10,
        "column_name": "From Email Address",
        "column_type": "String"
    },
    {
        "id": 103,
        "institution_id": 6,
        "column_number": 11,
        "column_name": "To Email Address",
        "column_type": "String"
    },
    {
        "id": 104,
        "institution_id": 6,
        "column_number": 12,
        "column_name": "Transaction ID",
        "column_type": "String"
    },
    {
        "id": 105,
        "institution_id": 6,
        "column_number": 13,
        "column_name": "Item Title",
        "column_type": "String"
    },
    {
        "id": 106,
        "institution_id": 6,
        "column_number": 14,
        "column_name": "Item ID",
        "column_type": "String"
    },
    {
        "id": 107,
        "institution_id": 6,
        "column_number": 15,
        "column_name": "Sales Tax",
        "column_type": "String"
    },
    {
        "id": 108,
        "institution_id": 6,
        "column_number": 16,
        "column_name": "Option 1 Name",
        "column_type": "String"
    },
    {
        "id": 109,
        "institution_id": 6,
        "column_number": 17,
        "column_name": "Option 1 Value",
        "column_type": "String"
    },
    {
        "id": 110,
        "institution_id": 6,
        "column_number": 18,
        "column_name": "Option 2 Name",
        "column_type": "String"
    },
    {
        "id": 111,
        "institution_id": 6,
        "column_number": 19,
        "column_name": "Option 2 Value",
        "column_type": "String"
    },
    {
        "id": 112,
        "institution_id": 6,
        "column_number": 20,
        "column_name": "Reference Txn ID",
        "column_type": "String"
    },
    {
        "id": 113,
        "institution_id": 6,
        "column_number": 21,
        "column_name": "Invoice Number",
        "column_type": "String"
    },
    {
        "id": 114,
        "institution_id": 6,
        "column_number": 22,
        "column_name": "Custom Number",
        "column_type": "String"
    },
    {
        "id": 115,
        "institution_id": 6,
        "column_number": 23,
        "column_name": "Quantity",
        "column_type": "String"
    },
    {
        "id": 116,
        "institution_id": 6,
        "column_number": 24,
        "column_name": "Receipt ID",
        "column_type": "String"
    },
    {
        "id": 117,
        "institution_id": 6,
        "column_number": 25,
        "column_name": "Balance",
        "column_type": "String"
    },
    {
        "id": 118,
        "institution_id": 6,
        "column_number": 26,
        "column_name": "Subject",
        "column_type": "String"
    },
    {
        "id": 119,
        "institution_id": 6,
        "column_number": 27,
        "column_name": "Note",
        "column_type": "String"
    },
    {
        "id": 120,
        "institution_id": 6,
        "column_number": 28,
        "column_name": "Balance Impact",
        "column_type": "String"
    }
]

export const institutionData = [
    {
        "id": 1,
        "key": "WLS_CHK",
        "name": "Wellsfargo Checking"
    },
    {
        "id": 2,
        "key": "WLS_VISA",
        "name": "Wellsfargo Visa"
    },
    {
        "id": 3,
        "key": "CONE_VISA",
        "name": "Capital One Visa"
    },
    {
        "id": 4,
        "key": "CH_VISA",
        "name": "Chase Visa"
    },
    {
        "id": 5,
        "key": "HD",
        "name": "Home Depot"
    },
    {
        "id": 6,
        "key": "PP",
        "name": "PayPal"
    },
    {
        "id": 7,
        "key": "LWS",
        "name": "Lowes"
    },
    {
        "id": 8,
        "key": "SND_CHK_HOUSE",
        "name": "Sound Checking - House"
    },
    {
        "id": 9,
        "key": "SND_CHK",
        "name": "Sound Checking - Christa"
    },
    {
        "id": 10,
        "key": "SND_VISA",
        "name": "Sound Visa"
    },
    {
        "id": 11,
        "key": "CC",
        "name": "Care Credit"
    },
    {
        "id": 12,
        "key": "AMZN_CHRIS",
        "name": "Amazon Chris"
    }
];
